name: Ejecutar Sistema de Admision

on:
  schedule:
    - cron: '0 12 * * *' # 8:00 AM Hora República Dominicana
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14.3'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests python-dotenv

      - name: Ejecutar script de Edison Clase
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EXCEL_LINK: ${{ secrets.EXCEL_LINK }}
          WHATSAPP_LINK: ${{ secrets.WHATSAPP_LINK }}
          LINK_DOCUMENTOS: ${{ secrets.LINK_DOCUMENTOS }}  # <--- AGREGAMOS ESTA LÍNEA
        run: python main.py

      - name: Guardar lista de enviados
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add logs/enviados.txt || true
          git commit -m "Update: Lista de enviados [skip ci]" || true
          git push origin main || true